Tangodict code improvements
autolab/Tango pull request #187
Opened 2020-12-10 19:50 UTC by clairecw

Fixes #171, and adds tests for TangoDictionary accordingly.

2020-12-11 20:30 UTC, fanpu commented
Hi @clairecw , thank you for your PR! It looks really good in general, and I really appreciate the fact that there are unit tests. A couple of more complicated unit tests would also be helpful. Do you have other instructions for end-to-end testing that you could share as well?

2020-12-12 21:27 UTC, clairecw commented
Hi @fanpu, thanks so much for the feedback! Yes, I've added unit tests testing a bit more functionality for the dictionary object specifically - if you could TAL when you get the chance and see if there's anything else you had in mind that'd be awesome! 
Lmk also if you'd like to see unit tests for the other Tango objects.

As for E2E tests, I suppose there could be tests for each of the functions in TangoServer, and maybe another file testing the endpoints themselves.

2020-12-12 23:15 UTC, fanpu commented
Great job and thanks! I've looked through the changes and tests and they look good, and I've also tested it with Autolab.

One last change before it's ready to be merged: could you use the [unittest](https://docs.python.org/3/library/unittest.html) methods for asserting the tests instead of the native Python assert? You can refer to [this file](https://github.com/autolab/Tango/blob/master/tests/testJobQueue.py) for examples.

2020-12-12 23:16 UTC, fanpu commented
Tests for other Tango objects would also definitely be greatly appreciated, see https://github.com/autolab/Tango/issues/183 for some ideas

2020-12-12 23:20 UTC, fanpu requested changes

2020-12-12 23:20 UTC, fanpu commented on tests/testObjects.py
> +        assert test_dict.keys() == []
Change to unittest assert

2020-12-13 02:44 UTC, clairecw commented on tests/testObjects.py
> +        assert test_dict.keys() == []
This makes sense! Thanks!

2020-12-13 04:17 UTC, fanpu approved these changes
Excellent job and thanks once again for your contributions!

2020-12-13 04:17 UTC, merged