Type annotations fixed
autolab/Tango pull request #200
Opened 2020-12-17 04:19 UTC by CCCodes

Fixes #185.

Changes proposed in this PR:
Add type annotations for
- jobManager.py
- jobQueue.py
- tangoObjects.py
- worker.py
- tango.py
- preallocator.py

Some type annotations are best guesses because it was hard to determine exactly what types were acceptable. I ran all unittests on it and got the same results with / and without the annotations, so there were no problems in those cases.

2020-12-21 18:02 UTC, fanpu commented
Hi @CCCodes, thank you for updating the PR based on my previous comments! Apologies for the delay in response, I'll be reviewing it now

2020-12-21 18:28 UTC, fanpu commented on tango.py
> +    def resetTango(self, vmms: list) -> None:
`list` should be `List[<some type]` instead, and can be imported with `from typing import List`

2020-12-21 18:52 UTC, fanpu requested changes
Great job overall and thanks so much for your contributions! There are some compound types and custom datatypes whose annotations are wrong but it's also partially the fault of the lack of a CI pipeline in Tango which means that you won't really be able to check if they are actually working. Could you address the comments, and once those are done it should be good to go!

2020-12-21 18:52 UTC, fanpu commented on jobQueue.py
> +    def getInfo(self) -> dict:
`Dict` should be capitalized and contain the type mapping, see https://docs.python.org/3/library/typing.html#typing.Dict

2020-12-21 18:52 UTC, fanpu commented on jobQueue.py
> +    def reuseVM(self, job: TangoJob) -> Optional['vm']:
'vm' is probably not a valid type

2020-12-21 18:52 UTC, fanpu commented on tangoObjects.py
> +def getRedisConnection() -> redis.StrictRedis:
Figuring out the type of this is tricky, it's actually `redis.client.Redis`. You can do it by installing [mypy](http://mypy-lang.org/), creating a test python file (say test.py), adding the following stub:

```
import redis
reveal_type(redis.StrictRedis(host='localhost', port=6379, db=0))
```

`reveal_type` is a feature from `mypy` that has an example here: https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#when-you-re-puzzled-or-when-things-are-complicated

2020-12-21 18:52 UTC, fanpu commented on tangoObjects.py
> +def TangoDictionary(object_name) -> 'TangoDictionary':
This should be `tangoObjects.TangoRemoteDictionary`

2020-12-21 18:52 UTC, fanpu commented on tangoObjects.py
> +    def values(self) -> list:
Same comment on list as before

2020-12-26 17:45 UTC, CCCodes commented
Thanks for the feedback, I will work on the changes now!

2021-01-10 17:54 UTC, fanpu approved these changes
Thanks for making the changes @CCCodes! I looked through the changes again and found a few more issues but I'll be able to take care of them. Merging changes into a temporary branch first in order to fix these issues. Once again thanks for your contributions!

2021-01-10 17:54 UTC, merged