Adding stress test script
autolab/Tango pull request #261
Opened 2024-10-27 17:57 UTC by dwang3851

Adds a script for basic stress test functionality. This script uses the Tango CLI to simulate various submissions scenarios. The number of submissions can be adjusted as well as the rate at which they are submitted. Required parameters include the autograder image, the path to the Tango directory, the job name, and the path to the job. 

Example command to run script:
- python3 stressTest.py --num_submissions 10 --submission_delay 1.0 --autograder_image autograding_image_py --tango_port 4567 --tango_path ~/Tango --job_name assessment1 --job_path ~/Tango/clients/job1/ 

To get metrics, simply add -get_metrics True to the end of this command, this will not spawn any new jobs.

2024-11-24 18:40 UTC, jhs-panda requested changes
Functionality works, just some nitpicks on how information is displayed/clarifying error messages. May also help to add some more screenshots to description of PR to make it clear to viewer how to use stress test + what results could look like.

2024-11-24 18:40 UTC, jhs-panda commented on stressTest.py
> +        f.write(f"Stress testing with {num_submissions} submissions\n")
add submission delay and job name, may help with easy searching if many stress tests are run at once or it all prints to same output file

2024-11-24 18:40 UTC, jhs-panda commented on stressTest.py
> +    submission_delay,
add check to ensure submission_delay is nonnegative (to catch in case they made a typo)

2024-11-24 18:40 UTC, jhs-panda commented on stressTest.py
> +
Add print statement to tell user that script has finished running if successful

2024-11-24 18:40 UTC, jhs-panda commented on stressTest.py
> +        print("Make sure logs are recorded in a log file")
Add to fill out LOGFILE in config.py so users don't need to trace through code (current error statement could be confusing)

2025-11-18 20:00 UTC, closed without merging

2025-11-18 20:01 UTC, KesterTan commented
This is already merged in copy-in, Soma based his stress test changes using this PR, closing for now